name: Deploy to Firebase

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm ci
      - name: Building the project
        run: npm run build
        env: 
          VUE_APP_GOOGLE_API_KEY: ${{ secrets.VUE_APP_GOOGLE_API_KEY }}
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: vue-earthquake
